name: Deploy to AWS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            mkdir -p ~/dirForwarderBot && cd ~/dirForwarderBot
            git init
            git remote add origin https://github.com/Alisher20010120/dirForwarderBot.git || true
            git fetch --all
            git reset --hard origin/main
            
            docker network create bot-network || true
            
            # Bazani ishga tushirish (agar o'chiq bo'lsa yoqadi, yo'q bo'lsa yaratadi)
            if [ ! "$(docker ps -q -f name=bot_db)" ]; then
                if [ "$(docker ps -aq -f status=exited -f name=bot_db)" ]; then
                    docker start bot_db
                else
                    docker run -d --name bot_db \
                      --network bot-network \
                      -e POSTGRES_USER=bot_user \
                      -e POSTGRES_PASSWORD=bot_password \
                      -e POSTGRES_DB=bot_database \
                      -v pgdata:/var/lib/postgresql/data \
                      postgres:15
                fi
            fi
            
            # Botni yangitdan build qilish
            docker build -t dir-bot .
            
            # Eski botni to'xtatish va o'chirish (xatosiz)
            docker stop dir-bot-cont || true
            docker rm dir-bot-cont || true
            
            # Yangi botni ishga tushirish
            docker run -d --name dir-bot-cont \
              --network bot-network \
              -e BOT_TOKEN="${{ secrets.BOT_TOKEN }}" \
              -e SPRING_DATASOURCE_URL=jdbc:postgresql://bot_db:5432/bot_database \
              -e SPRING_DATASOURCE_USERNAME=bot_user \
              -e SPRING_DATASOURCE_PASSWORD=bot_password \
              -p 8080:8080 \
              dir-bot